;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        artist-backward-char
        artist-next-line
        beginning-of-visual-line
        comment-dwim
        end-of-buffer
        handle-switch-frame
        indent-for-tab-command
        indent-new-comment-line
        inf-clojure-eval-defun
        isearch-printing-char
        iy-go-to-char--command
        iy-go-up-to-char
        kill-region
        kill-sexp
        matlab-electric-comment
        mouse-yank-primary
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-return
        org-self-insert-command
        org-todo
        org-yank
        picture-clear-column
        picture-self-insert
        puppet-indent-line
        puppet-interpolate
        smart-line-beginning
        sp-backward-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-remove-active-pair-overlay
        sp-unwrap-sexp
        split-line
        string-inflection-all-cycle
        suspend-frame
        wdired-downcase-word
        windows-to-posix-path
        xterm-paste
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        helm-confirm-and-exit-minibuffer
        puppet-align-block
        save-buffers-kill-terminal
        suspend-frame
        ))
