;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        artist-backward-char
        artist-next-line
        comment-dwim
        end-of-buffer
        handle-switch-frame
        indent-for-tab-command
        isearch-printing-char
        iy-go-to-char--command
        iy-go-up-to-char
        kill-region
        matlab-electric-comment
        mouse-yank-primary
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-return
        org-self-insert-command
        org-yank
        picture-clear-column
        picture-self-insert
        puppet-indent-line
        puppet-interpolate
        smart-line-beginning
        sp-backward-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-remove-active-pair-overlay
        split-line
        suspend-frame
        wdired-downcase-word
        xterm-paste
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        puppet-align-block
        save-buffers-kill-terminal
        suspend-frame
        ))
